# Generated by Django 5.0.2 on 2024-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
