# Generated by Django 5.0.2 on 2024-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
