# Generated by Django 5.0.2 on 2024-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
