# Generated by Django 5.0.2 on 2024-05-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction',
        ),
    ]
