# Generated by Django 5.0.2 on 2024-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_remove_coupon_is_active_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncategory',
            options={'verbose_name': 'Promotion Category', 'verbose_name_plural': 'Promotion Categories'},
        ),
    ]
