# Generated by Django 5.0.2 on 2024-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_promotioncategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
