# Generated by Django 5.0.2 on 2024-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_discount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotioncategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
