# Generated by Django 5.0.2 on 2024-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_promotion_status_promotioncategory_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='promotion_c_code_3b6474_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expiry'], name='promotion_c_expiry_4eba3d_idx'),
        ),
    ]
