# Generated by Django 5.0.2 on 2024-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
