# Generated by Django 5.0.2 on 2024-05-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('promotion', '0002_remove_coupon_is_active_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.coupon'),
        ),
    ]
