# Generated by Django 5.0.2 on 2024-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
    ]
