# Generated by Django 5.0.2 on 2024-06-19 17:23

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_email_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=functools.partial(core.models.image_upload_path, *(), **{'folder': 'products'}))),
            ],
        ),
    ]
