# Generated by Django 5.0.2 on 2024-06-20 09:45

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, upload_to=functools.partial(core.models.image_upload_path, *(), **{'folder': 'avatars'})),
        ),
    ]
