# Generated by Django 5.0.2 on 2024-05-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
    ]
