# Generated by Django 5.0.2 on 2024-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderstatus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('name',), 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
    ]
