# Generated by Django 5.0.2 on 2024-05-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_amount_paid_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
