# Generated by Django 5.0.2 on 2024-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
