# Generated by Django 5.0.2 on 2024-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
