# Generated by Django 5.0.2 on 2024-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_price',
            field=models.FloatField(),
        ),
    ]
